---
- name: AWX 템플릿 배포
  hosts: genie_vm
  vars:
    base_path: 'genie'
    genie_ip: 'localhost'
  gather_facts: no
  tasks:

    - name: AWX 초기 관리자 패스워드 추출
      shell: kubectl get -n awx secret awx-admin-password -o jsonpath="{.data.password}" | base64 --decode
      register: admin_password

    # Nextcloud
    - name: Create nextcloud deploy playbook
      awx.awx.job_template:
        name: testttt
        job_type: "run"
        inventory: genie_inventory
        project: tj
        playbook: test.yml
        credentials:
          - "automation_controller_credential"
        state: "present"
        controller_host: "http://{{ genie_ip }}:80"
        controller_username: admin
        controller_password: "{{ admin_password.stdout }}"
        extra_vars: 
          TEXT_VAL: 'gkgkgkgkgkgkjdfkjaklsdfsad'