---
- name: State Httpd
  hosts: localhost
  vars:
    favcolor: Stopped
  gather_facts: no
  tasks:
##### Deploy VirtualMachine #####

    - name: 배포한 가상머신 정보 수집
      cs_instance_info:
        api_url: "{{ lookup('env', 'MOLD_API_URL') }}"
        api_key: "{{ lookup('env', 'MOLD_API_KEY') }}"
        api_secret: "{{ lookup('env', 'MOLD_SECRET_KEY') }}"
        name: nextcloud-deploy-vm1
      delegate_to: localhost
      register: vm
    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ vm }}"

    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ vm.instances[0].nic[0].ipaddress }}"

    - name: 배포 가상머신 인메모리 inventory에 등록
      add_host:
        hostname: "{{ vm.instances[0].nic[0].ipaddress }}"
        groups:
          - deployVmIp

    - name: ssh
      ansible.builtin.command: ssh root@{{ vm.instances[0].nic[0].ipaddress }} "systemctl status httpd"
      register: result
    - name: ssh debug
      debug:
        msg: "{{ result.stdout }}"


    # - debug: var=services_state.ansible_facts.services["httpd.service"].state
    # - debug: var=services_state.ansible_facts.services["mysqld.service"].state


    # 서비스 그룹 등록

    # 서비스 단위 전체 삭제

    # 서비스 단위별 상태 체크




    # 서비스 단위별 상태 등록

    # 서비스 그룹 상태 최종 업데이트