---
- name: State Httpd
  hosts: localhost
  gather_facts: no
  tasks:
##### Deploy VirtualMachine #####

    - name: 배포한 가상머신 정보 수집
      cs_instance_info:
        api_url: "{{ lookup('env', 'MOLD_API_URL') }}"
        api_key: "{{ lookup('env', 'MOLD_API_KEY') }}"
        api_secret: "{{ lookup('env', 'MOLD_SECRET_KEY') }}"
        name: nextcloud-deploy-vm1
      delegate_to: localhost
      register: vm

    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ vm.instances[0].nic[0].ipaddress }}"

    - name: 배포 가상머신 인메모리 inventory에 등록
      add_host:
        hostname: "{{ vm.instances[0].nic[0].ipaddress }}"
        groups:
          - deployVmIp
    
##### State Httpd #####
- name: "State Httpd"
  hosts: deployVmIp
  gather_facts: no
  vars:
    - service: httpd.service
  tasks:
    - name: populate service facts
      ansible.builtin.service_facts:
    - debug: var=services[service]['status']
    - debug:
        msg: "{{ services[service]['status'] }}"

##### Save State Httpd #####
- name: "Save State Httpd"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: register resource
      ansible.builtin.command: python2 /home/runner/mold_genie_api.py \
        -c listAutomationDeployedResource \
        -ip 10.10.254.168 \
        -ak ArfB-Y2r8LXfeWBmyNzpCgk1aOzg2s_O8PYXLX6uNRKg7lOWyd16nTshg4fsmEWs0dnEk8PIb0do0eczlysFpg \
        -sk g8Cghfff4Fc-n_iEYoHDJxnIv6sB0wJFx1CwtgEvBwJZw-W41Dblg7FA-oWN_EfO_C__f90STJDOPwlx3ftkUg \
        -n Nextcloud
      register: list
    - name: debug list stdout
      debug:
        msg: "{{ list.stdout }}"
    - name: debug list stdout_lines
      debug:
        msg: "{{ list.stdout_lines }}"
    - name: select value
      debug:
        msg: "{{ list.stdout_lines.listautomationdeployedresourceresponse.automationdeployedresource[0].id }}"


    # - debug: var=services_state.ansible_facts.services["httpd.service"].state
    # - debug: var=services_state.ansible_facts.services["mysqld.service"].state


    # 서비스 그룹 등록

    # 서비스 단위 전체 삭제

    # 서비스 단위별 상태 체크

    # 서비스 단위별 상태 등록

    # 서비스 그룹 상태 최종 업데이트